# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Translating the project..."
      $output = sourceanalyzer -b CoreApp C:\VulnerableWebApps\VulnerableCoreApp-master\
      Write-Host "$output"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Executing scancentral job and capturing job token..."
      $output = scancentral -sscurl https://fortify.cw:8443/ssc -ssctoken 07f6ee7d-3d2c-4d0a-b875-36ca9c673cc0 start ‑upload -versionid 10016 -uptoken 07f6ee7d-3d2c-4d0a-b875-36ca9c673cc0 -b CoreApp -scan -debug
      
      # Iterate through each line
      foreach ($line in $lines) { 
        if ($line -like "*token:*"){
          # Split the line at "token: " and get the right side
          $token = $line.Split(":")[1].Trim()
          Write-Host "Captured token: $token"
        } 
      }